// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNMRHTzusNJ2OLWWBc_LfUQIolshu2PQ',
    appId: '1:234170188134:web:cab06ce49597506d3d88a7',
    messagingSenderId: '234170188134',
    projectId: 'greenisland-31c56',
    authDomain: 'greenisland-31c56.firebaseapp.com',
    storageBucket: 'greenisland-31c56.firebasestorage.app',
    measurementId: 'G-9T612PYP2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZge8QYOX3YeF5S2Zcrmzo442JwCBaHU',
    appId: '1:234170188134:android:6e5acba8ada4c2c83d88a7',
    messagingSenderId: '234170188134',
    projectId: 'greenisland-31c56',
    storageBucket: 'greenisland-31c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXxISwpuBCv8nWSNb0eEEvSBn2IDfMEQ',
    appId: '1:234170188134:ios:c8795064ab6180103d88a7',
    messagingSenderId: '234170188134',
    projectId: 'greenisland-31c56',
    storageBucket: 'greenisland-31c56.firebasestorage.app',
    iosBundleId: 'com.example.smartplantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXxISwpuBCv8nWSNb0eEEvSBn2IDfMEQ',
    appId: '1:234170188134:ios:c8795064ab6180103d88a7',
    messagingSenderId: '234170188134',
    projectId: 'greenisland-31c56',
    storageBucket: 'greenisland-31c56.firebasestorage.app',
    iosBundleId: 'com.example.smartplantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSNMRHTzusNJ2OLWWBc_LfUQIolshu2PQ',
    appId: '1:234170188134:web:1a09ad6f56dadf383d88a7',
    messagingSenderId: '234170188134',
    projectId: 'greenisland-31c56',
    authDomain: 'greenisland-31c56.firebaseapp.com',
    storageBucket: 'greenisland-31c56.firebasestorage.app',
    measurementId: 'G-DJ7GLY425K',
  );
}
